const experiences = [
  {
    key: 1,
    image: "images/tomresearch.png",
    title: "Independent Research: Ethical Issues with Autonomous Vehicles",
    date: "June 2020 - November 2020",
    location: "San Jose, CA",
    position: "Research Conductor, Analyzer, and Author",
    description: "Conducted independent research under guidance of Stanford Professor, Tom Kosnik Researched about the ethical dilemmas regarding autonomous vehicles. Used surveying and data analysis to obtain and analyze data"
  },
  {
    key: 2,
    image: "images/cairolab.png",
    title: "University of Colorado Boulder: Summer AI Research Program",
    date: "June 2020 - November 2020",
    location: "Boulder, CO",
    position: "Research Assistant",
    description: "Collaborated with grad student Aaquib Tabrez’s research about Human-AI collaboration in the Cairo Lab Developed online car racing game generated by AI; Designed program utilizing JS, Python, mySQL, HTML, CSS"
  },
  {
    key: 3,
    image: "images/stanfordneurodiversity.jpeg",
    title: "Stanford Medicine: SNP Reach",
    date: "June 2020 - July 2020",
    location: "Stanford, CA",
    position: "Student",
    description: "Proposed a pitch to implement and facilitate changes to accommodate for neurodiversity within the local school community"
  },
  {
    key: 4,
    image: "images/stanfordneurodiversity.jpeg",
    title: "Hwarang Youth Foundation",
    date: "June 2018 - May 2021",
    location: "Saratoga, CA",
    position: "Chairperson of Silicon Valley District",
    description:"Led a district of three chapters (11-15 members per chapter) Organized volunteering events, established MOU partnership with K-Group, collaborated with FCSN (special-needs oriented organization)"
  },
  {
    key: 5,
    image: "images/stanfordneurodiversity.jpeg",
    title: "National Academy of Athletics",
    date: "June 2022 - July 2022",
    location: "San Jose, CA",
    position: "Camp Director",
    description:"Hired as a Camp Director for NAofA sports camps. Organized and supervised football and volleyball camps for 20+ students."
  }

]

export default experiences;
