const experiences = [
  {
    key: 1,
    image: "images/tomresearch.png",
    title: "Independent Research: The Social Dilemma of Autonomous Vehicles",
    date: "June 2020 - November 2020",
    location: "San Jose, CA",
    position: "Research Conductor, Analyzer, and Author",
    description: "Conducted independent research under guidance of Stanford Professor, Tom Kosnik Researched about the ethical dilemmas regarding autonomous vehicles. Used surveying and data analysis to obtain and analyze data"
  },
  {
    key: 2,
    image: "images/cairolab.png",
    title: "University of Colorado Boulder: Summer AI Research Program",
    date: "June 2020 - November 2020",
    location: "Boulder, CO",
    position: "Research Assistant",
    description: "Collaborated with grad student Aaquib Tabrez’s research about Human-AI collaboration in the Cairo Lab Developed online car racing game generated by AI; Designed program utilizing JS, Python, mySQL, HTML, CSS"
  }







]







export default experiences;
